### ISSUE TITLE
Can only specify files in current directory for CLI

### ISSUE THREAD

**Issue by MarkMcCulloh** [Cohesible/synapse#5]
Does not work:

```shell
synapse deploy ./hello.ts
synapse deploy folder/hello.ts
synapse run ./hello.ts
# No executable found matching: ./hello.ts [available: hello.ts]
````

The only form that works for either command:

```shell
synapse deploy hello.ts
````

**Comment by JadenSimon** [comment]
> synapse run ./hello.ts

Oh wow surprised this slipped past me.

> synapse deploy folder/hello.ts

Good find, I assume you're using either no `tsconfig.json` or an empty one. I've mostly stuck to the defaults used by `tsc` but here's another case of where the default doesn't make sense.

**Comment by JadenSimon** [comment]
> I've mostly stuck to the defaults used by tsc but here's another case of where the default doesn't make sense.

Turns out my default was just not aligned with `typescript`. That was an easy fix though.
