### ISSUE TITLE
Cannot `run` another file without compiling it first

### ISSUE THREAD

**Issue by MarkMcCulloh** [Cohesible/synapse#7]
### Reproduction Steps 

1. `synapse init`
2. `synapse compile hello.ts` (default created file)
3. Create `whatever.ts` with a dummy exported main function
4. `synapse run whatever.ts`

**Error:**

```
No executable found matching: whatever.ts [available: hello.ts]
```

To run the new file, it needs to be `synapse compiled`d first

### System Info

* version: 0.0.16
* revision: 8c78f2dee91d5b1fb12cdda42864674d824a16e3
* host: darwin-arm64-LE
* os-version: 23.6.0

**Comment by MarkMcCulloh** [comment]
Makes sense, I noticed this in other cases as well but didn't want to guess about anything underlying. My current dev hot-loop is using `synapse run` so that's where it's poking me the most.

**Comment by JadenSimon** [comment]
> My current dev hot-loop is using synapse run so that's where it's poking me the most.

Out of curiosity, are you using `main` functions as a way to test/iterate on sub-components within a bigger project? I personally find myself doing this.

**Comment by MarkMcCulloh** [comment]
Basically yes, although my project is very small so there are not many sub-components. If I had more I would probably do the same thing.
